### ISSUE TITLE
typo in example of Scalar Product

### ISSUE THREAD

**Issue by PrzemekN** [thomas-haslwanter/sapy#1]
Hi,
In chapter 1 there is a little typo, you double write ay but the last one should be az.

take a look please at my attached file

![typo in chapter 1](https://user-images.githubusercontent.com/27012543/133881389-318c6407-ca8b-4239-9e34-7071b4500bda.jpg)

regards
Przemek Nawrocki

**Comment by thomas-haslwanter** [comment]
Thank you!
I have fixed it, and put it in the Errata.
